# This is a basic workflow to help you get started with Actions

name: Deploy-To-Droplet

# Controls when the workflow will run
on: [workflow_dispatch]
# on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the files
        uses: actions/checkout@main
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
                    
      - name: Install npm dependencies
        run: npm install
        
      - name: Run build task
        run: npm run build
        
      - name: directory after build  
        run: |
            ls ${{github.workspace}}
        
      - name: Deploy to DigitalOcean Server
        uses: easingthemes/ssh-deploy@main        
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DROPLET_NYC3_TALENT_2_01_PVT }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/talentfactories-ui/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          #EXCLUDE: "/dist/, /node_modules/"
          EXCLUDE: "/node_modules/"
